server:
  # please don't modify it if you don't know what you are doing
  port: ${PORT:8080}

spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/testdb
#    hikari:
#      connection-timeout: 30000
#      maximum-pool-size: 10
  datasource:
    url: jdbc:mysql://localhost:3306/movie?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
#  flyway:
#    baseline-on-migrate: true

